version: "3.9"

services:
  python-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      FLASK_APP: api.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      GUNICORN_TIMEOUT: 120
      GUNICORN_WORKERS: 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
