version: '3.8'

services:
  electionguard-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electionguard-js-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - electionguard-dev

networks:
  electionguard-dev:
    driver: bridge
